In [1]:
import numpy as np


## Datatypes & attributes

In [2]:
#Numpy main datatype is ndarray(n-diamensional attay)
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [22]:
a2=np.array([[1,2.,3],
            [4,5.,6]])

a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.shape

(3,)

In [17]:
a2.shape

(2, 3)

In [18]:
a3.shape

(2, 3, 3)

In [19]:
 a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
# this upper one shows the dimaension of our table , that is 1D , 2D or 3D

In [23]:
a1.dtype ,a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [25]:
a1.size , a2.size , a3.size # this tells that how much elements we have in our array

(3, 6, 18)

In [26]:
type(a1), type(a2), type(a3) # all array in numpy is of nd array

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [28]:
# Create a data frame from numpy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## 2. Creatin numpy arrays

In [30]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [35]:
# shift+tab will open the functions docstring
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
ones.dtype

dtype('float64')

In [37]:
type(ones)

numpy.ndarray

In [39]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [42]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[5, 8, 0, 8, 8],
       [3, 1, 7, 5, 4],
       [7, 7, 8, 7, 9]])

In [43]:
random_array.size

15

In [44]:
random_array.shape

(3, 5)

In [45]:
random_array2= np.random.random((5,3))
random_array2

array([[0.26865072, 0.340697  , 0.52674977],
       [0.24333951, 0.36598871, 0.89291972],
       [0.40327036, 0.46709452, 0.81374255],
       [0.00796957, 0.56641157, 0.41247829],
       [0.23363111, 0.75022496, 0.78113907]])

In [46]:
random_array2.size

15

In [58]:
random_array3=np.random.rand(5,3) 
random_array3

array([[0.61252607, 0.72175532, 0.29187607],
       [0.91777412, 0.71457578, 0.54254437],
       [0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895]])

In [99]:

np.random.seed(seed=0) # if we want to share our code , and its machine is taking another output ours are another , so we can use seed , so that it would helps in futute
random_array4=np.random.randint(10,size=(5,3))
random_array4
# other than random.seed numbers , all are pseudo random numbers , which means , seed is giving random value at every time when we runs it

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [100]:
random_array4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [101]:
np.unique(random_array4) # it gonna print unique elements

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [103]:
a3.shape

(2, 3, 3)

In [104]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a2[1]

array([4., 5., 6.])

In [113]:
# 7,7

## 4. Practical example - numpy in action

In [123]:
# converting images into array
# we can convert images into numbers by identifying pattersn into numbers

In [124]:
# from matplotlib.image import imread?

<img src="images/panda.png"/>

In [128]:
from matplotlib.image import imread

panda=imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [129]:
panda.size , panda.shape, panda.ndim #ndim attribute returns the number of dimensions of the underlying data, by definition it is 1 for series objects. Example #1: Use Series. ndim attribute to find the dimension of the given series object

(24465000, (2330, 3500, 3), 3)

<img src="images/car-photo.png"/>

In [132]:
car=imread("images/car-photo.png")

In [135]:
print (type(car))

<class 'numpy.ndarray'>


In [136]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src="images/dog-photo.png"/>

In [147]:
dog=imread("images/dog-photo.png")

In [148]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

In [149]:
print(type(dog))

<class 'numpy.ndarray'>
